In [5]:
import numpy as np

# Arrays

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [15]:
# Get dimension
a.ndim

1

In [16]:
# Get shape
a.shape

(3,)

In [11]:
b = np.array([[9.0, 8.0, 7.0], [5.0, 3.2, 4.1]])
b

array([[9. , 8. , 7. ],
       [5. , 3.2, 4.1]])

In [17]:
# Get dimension
b.ndim

2

In [18]:
# Get shape (row, col)
b.shape

(2, 3)

In [20]:
# Get type
a.dtype

dtype('int32')

In [21]:
b.dtype

dtype('float64')

In [22]:
# Get size of each element in byte (32bit -> 4byte)
a.itemsize

4

In [23]:
b.itemsize

8

In [24]:
# Get number of elements
a.size

3

In [25]:
b.size

6

# Accessing/Changing elements, rows, cols

In [27]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
# Get specific element
a[0, 1]

2

In [29]:
a[-1, -1]

14

In [32]:
# Get everything from a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
# Get everything from a specific column
a[:, 3]

array([ 4, 11])

In [36]:
# [startindex:endindex:stepsize]
# Get elements from col [1-6) for row 0 in steps of 2
a[0, 1:6:2]

array([2, 4, 6])

In [42]:
# Change value
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [43]:
# Change all values in a col
a[:, 2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [46]:
# Change all values in a row
a[0, :] = 1
a

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [49]:
a[0, :] = [1, 2, 3, 4, 5, 6, 7]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [61]:
# Transpose
a.T

array([[ 1,  8],
       [ 2,  9],
       [ 3,  2],
       [ 4, 11],
       [ 5, 12],
       [ 6, 20],
       [ 7, 14]])

In [62]:
# 3D array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
# Getting values
b[0, 1, 1]

4

In [68]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [69]:
b[0, :, :]

array([[1, 2],
       [3, 4]])

In [71]:
b[0, :, :] = 1
b

array([[[1, 1],
        [1, 1]],

       [[5, 6],
        [7, 8]]])

# Initializing different types of arrays

In [73]:
# All 0s matrix
np.zeros(5) # 1D 5 elements

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((2, 3)) # 2D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros((2, 3, 4)) # 3D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [77]:
# All 1s matrix
np.ones((3, 7), dtype='int32')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [79]:
# Any other number
np.full((2, 3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [87]:
# Any other number (full_like)
np.full_like(a, 4) # Takes the shape of a and fills with 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [94]:
# Playing with random
np.random.rand(4, 2)

array([[0.08992573, 0.42625809],
       [0.88792305, 0.46538366],
       [0.48102123, 0.64146335],
       [0.45358304, 0.29812818]])

In [92]:
np.random.random_sample()

0.4940440882376811

In [119]:
# Random interger values
np.random.randint(7, size=a.shape) # Random number from [0-7)

array([[5, 4, 5, 3, 0, 1, 3],
       [3, 5, 3, 3, 0, 0, 4]])

In [120]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [124]:
# Reapeat
arr = np.array([[1, 2, 3]])
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [122]:
arr = np.array([1, 2, 3])
np.repeat(arr, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [126]:
# Activity
# Build this 2D array
'''
1 1 1 1 1
1 0 0 0 1
1 0 5 0 1
1 0 0 0 1
1 1 1 1 1
'''

# Use tricks

In [127]:
# Outer borders
output = np.ones((5, 5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [128]:
# Inner Zeroes
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
# Fill the inner part with zeros
output[1:-1, 1:-1] = zeros # Same as output[1:4, 1:4] = zeros
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
# Finally add the 5 in the middle
output[2, 2] = 5
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 5., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful when copying arrays

In [138]:
a = np.array([1, 2, 3])
b = a # b just references a, does not copy
b[0] = 100
b, a

(array([100,   2,   3]), array([100,   2,   3]))

In [140]:
# Actual way to copy
b = a.copy()
b[0] = 200
b, a

(array([200,   2,   3]), array([100,   2,   3]))

# Mathematics

In [150]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [151]:
a = a + 2
a

array([3, 4, 5, 6])

In [152]:
a = a - 2
a

array([1, 2, 3, 4])

In [154]:
a = a * 2
a

array([ 4,  8, 12, 16])

In [156]:
a = a / 2
a

array([1., 2., 3., 4.])

In [161]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [162]:
a+b

array([2., 4., 6., 8.])

In [163]:
a*b

array([ 1.,  4.,  9., 16.])

In [158]:
a ** 2

array([ 1.,  4.,  9., 16.])

In [159]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [164]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [165]:
np.tan(a*b)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224])

# Linear algebra

In [178]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [179]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [180]:
# Multiple matrices
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [181]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [182]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
np.max(stats) # stats.max()

6

In [193]:
np.max(stats, axis=1) # Get max row wise

array([3, 6])

In [194]:
np.max(stats, axis=0) # Get max column wise

array([4, 5, 6])

In [196]:
np.min(stats)

1

In [198]:
np.sum(stats)

21

In [199]:
np.prod(stats)

720

In [200]:
np.diff(stats)

array([[1, 1],
       [1, 1]])

In [201]:
a = np.array([1, 5, 6, 3, 2, 0, -1, 7])
a

array([ 1,  5,  6,  3,  2,  0, -1,  7])

In [202]:
np.diff(a)

array([ 4,  1, -3, -1, -2, -1,  8])

# Reorganizing arrays

In [203]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [206]:
before.shape

(2, 4)

In [205]:
# Can reshape only is number of elements is same.
before.reshape((8, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [209]:
before.reshape((4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [210]:
before.reshape((2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [215]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.stack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [230]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

h1, h2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [231]:
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])